# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: PIG 镜像 action

on:
  push:
    branches: [ jdk17,jdk17-dev ]
  pull_request:
    branches: [ jdk17,jdk17-dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu'

      - name: mvn clean install
        run: mvn clean install

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

      - name: Build and push Docker images
        run: |
          docker-compose build
          registry="registry.cn-hangzhou.aliyuncs.com/musix/"
          for service in $(docker-compose config --services); do
            if [ "$service" != "musi-redis" ]; then
              docker tag ${service}:latest ${registry}${service}:latest
              docker push ${registry}${service}:latest
            else
              echo "Skipping musi-redis service"
            fi
          done
