name: 同步代码

on:
  push:
    branches: [ master,jdk17 ]
  pull_request:
    branches: [ master,jdk17 ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master #同步至 gitlink
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:musi-mesh/musi.git"
          destination-repo: "git@code.gitlink.org.cn:lengleng/musi.git"
